### ISSUE TITLE
我觉得小说用.md文件写在github上会好看些

### ISSUE THREAD

**Issue by wobuchizhunao** [Kuangcp/GhostPushLight#1]

**Comment by Kuangcp** [comment]
我也想啊～～可是这是下载的一个鬼吹灯完整txt文件
我又用正则切成了一章一章的～～等我学py了再思考固定字符切分行～就方便看了

**Comment by Kuangcp** [comment]
再加上上一章下一章～目录的链接进去就方便了，思路倒是不难～～要是你有空也可以帮忙折腾下😂
